name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - pip
  - sphinx=8.1.3
  - nbsphinx=0.9.5
  - sphinx_rtd_theme=3.0.1
  - pandoc=3.6
  - pip:
      - ipython==8.30.0
      - nbsphinx-link==1.3.1